//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiqtChartApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamData
    {
        public int Num { get; set; }
        public string Sec { get; set; }
        public string Yvalue { get; set; }
        public string Xvalue { get; set; }
    }
}
